"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useRef, useState, useSyncExternalStore } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { GENESIS_START, getEventStatus, SITE_INFO, VOTING_CATEGORIES, type GenesisEvent } from "@/config/genesis";
import { ADMIN_API_BASE } from "@/config/admin-api";

gsap.registerPlugin(ScrollTrigger);

const subscribeToClock = (onChange: () => void) => { const timer = window.setInterval(onChange, 1000); return () => window.clearInterval(timer); };
const useMounted = () => useSyncExternalStore(() => () => undefined, () => true, () => false);

export function Countdown({ target = GENESIS_START, compact = false }: { target?: string; compact?: boolean }) {
  const mounted = useMounted();
  const [left, setLeft] = useState([0, 0, 0, 0]);
  const previous = useRef(left);
  useEffect(() => { const tick = () => { const delta = Math.max(0, new Date(target).getTime() - Date.now()); setLeft([Math.floor(delta / 86400000), Math.floor(delta / 3600000) % 24, Math.floor(delta / 60000) % 60, Math.floor(delta / 1000) % 60]); }; const firstTick = window.setTimeout(tick, 0); const timer = window.setInterval(tick, 1000); return () => { window.clearTimeout(firstTick); window.clearInterval(timer); }; }, [target]);
  useEffect(() => { if (!mounted) return; const changed = left.map((value, index) => value !== previous.current[index] ? `.time-unit:nth-child(${index + 1}) strong` : null).filter(Boolean).join(","); if (changed) gsap.fromTo(changed, { y: -8, opacity: .35 }, { y: 0, opacity: 1, duration: .28, stagger: .02, ease: "power2.out" }); previous.current = left; }, [left, mounted]);
  return <div className={`countdown ${compact ? "countdown-compact" : ""}`} aria-label={`Countdown to ${target}`}>{left.map((value, index) => <div className="time-unit" key={index}><strong>{mounted ? String(value).padStart(2, "0") : "00"}</strong><span>{["Days", "Hours", "Minutes", "Seconds"][index]}</span></div>)}</div>;
}
export function GenesisCountdown() { const live = useSyncExternalStore(subscribeToClock, () => Date.now() >= new Date(GENESIS_START).getTime(), () => false); return live ? <div className="live-state">GENESIS IS LIVE</div> : <Countdown />; }
function AdminLoginModal({ onClose }: { onClose: () => void }) { const router = useRouter(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch(`${ADMIN_API_BASE}/admin/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); if (!response.ok) throw new Error(); const data = await response.json(); sessionStorage.setItem("genesis_admin_token", data.access_token); onClose(); router.push("/admin"); } catch { setError("Invalid username or password"); } finally { setLoading(false); } }; return <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><dialog className="admin-login" open aria-labelledby="admin-login-title"><button className="modal-close" type="button" onClick={onClose} aria-label="Close">×</button><span className="eyebrow">PRIVATE ACCESS</span><h2 id="admin-login-title">Admin login</h2><form onSubmit={submit}><label htmlFor="admin-username">Username</label><input id="admin-username" autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} required /><label htmlFor="admin-password">Password</label><input id="admin-password" type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required />{error && <p className="admin-error" role="alert">{error}</p>}<button className="button" disabled={loading} type="submit">{loading ? "Checking..." : "Enter dashboard"}</button></form></dialog></div> }
export function Navbar() { const pathname = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false); const [adminOpen, setAdminOpen] = useState(false); const clickTimes = useRef<number[]>([]); const handleLogoClick = (event: React.MouseEvent<HTMLAnchorElement>) => { event.preventDefault(); setOpen(false); if (pathname !== "/") router.push("/"); const now = Date.now(); clickTimes.current = [...clickTimes.current.filter((time) => now - time <= 2000), now]; if (clickTimes.current.length >= 4) { clickTimes.current = []; setAdminOpen(true); } }; return <><header className="navbar"><Link href="/" className="brand" onClick={handleLogoClick}><span>G/2</span> GENESIS</Link><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? "CLOSE" : "MENU"}</button><nav className={open ? "nav-links open" : "nav-links"}>{[["HOME", "/"], ["EVENTS", "/events"], ["PASSES", "/passes"], ["ABOUT", "/about"]].map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}</Link>)}</nav></header>{adminOpen && <AdminLoginModal onClose={() => setAdminOpen(false)} />}</> }
export function Footer() { return <footer><div><span className="eyebrow">GENESIS 2.0</span><p>{SITE_INFO.college}</p></div><div className="footer-links"><Link href="/">Home</Link><Link href="/events">Events</Link><Link href="/passes">Passes</Link><Link href="/about">About</Link></div><small>Built for the beginning · 2026</small></footer> }
export function SectionHeading({ kicker, title, copy }: { kicker: string; title: string; copy?: string }) { return <div className="section-heading"><span className="eyebrow">{kicker}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div> }
export function StatusBadge({ event }: { event: GenesisEvent }) { if (!event.startTime || !event.endTime) return null; const status = getEventStatus(event.startTime, event.endTime); return <span className={`status status-${status.toLowerCase()}`}>{status}</span> }
export function EventCard({ event }: { event: GenesisEvent }) { return <article className="event-card"><div className="event-visual"><span>{event.visual}</span><i>{event.category}</i></div><div className="event-body"><div className="event-meta"><span>{new Date(`${event.date}T00:00:00+05:30`).toLocaleDateString("en-IN", { day: "2-digit", month: "short" })}</span>{event.startTime && event.endTime && <StatusBadge event={event} />}</div><h3>{event.title}</h3><p>{event.description}</p>{event.startTime && event.endTime && <div className="event-time">{new Date(event.startTime).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Kolkata" })} — {new Date(event.endTime).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Kolkata" })} IST</div>}{event.route && <Link className="text-link" href={event.route}>Explore event <span>↗</span></Link>}</div></article> }
export function PassCard() { return <div className="pass-card"><div><span className="eyebrow">GENESIS PASS · 2026</span><h3>Rahul Kumar</h3><p>24ME001</p></div><div className="qr-placeholder">QR<br />SPACE</div></div> }
export function VoterPreview() { const [category, setCategory] = useState(VOTING_CATEGORIES[0]?.id ?? ""); const [candidate, setCandidate] = useState(""); const candidates = ["Aarav S.", "Ananya R.", "Kabir M.", "Meera P."]; return <div className="voter-preview"><div className="preview-label"><span className="eyebrow">VOTER PREVIEW</span><span className="preview-status">PREVIEW ONLY</span></div><div className="voter-step"><span>01</span><div><h3>Choose a category</h3><div className="category-tabs">{VOTING_CATEGORIES.map(item => <button className={category === item.id ? "category-tab selected" : "category-tab"} key={item.id} onClick={() => { setCategory(item.id); setCandidate(""); }}>{item.name}</button>)}</div></div></div><div className="voter-step"><span>02</span><div><h3>Select your pick</h3><div className="candidate-options">{candidates.map(name => <button className={candidate === name ? "candidate-option selected" : "candidate-option"} key={name} onClick={() => setCandidate(name)}><span className="radio-dot" />{name}<b>{candidate === name ? "SELECTED" : ""}</b></button>)}</div></div></div><div className="voter-submit"><p>{candidate ? `Your pick: ${candidate}` : "Select one candidate to continue"}</p><button className="button" disabled={!candidate} type="button">Submit vote <span>↗</span></button></div></div> }
export function PageShell({ children }: { children: React.ReactNode }) { const shell = useRef<HTMLDivElement>(null); useEffect(() => { if (!shell.current) return; const context = gsap.context(() => { const entrance = gsap.utils.toArray<HTMLElement>(".hero-grid > *, .page-heading > *, .spotlight-heading > *, .pass-heading > *"); gsap.fromTo(entrance, { autoAlpha: 0, y: 42 }, { autoAlpha: 1, y: 0, duration: .85, stagger: .12, ease: "power3.out" }); gsap.utils.toArray<HTMLElement>("main > .section, .schedule.section, .about-sections.section").forEach((element) => { gsap.fromTo(element, { autoAlpha: 0, y: 44 }, { autoAlpha: 1, y: 0, duration: .8, ease: "power2.out", scrollTrigger: { trigger: element, start: "top 88%", once: true } }); }); ScrollTrigger.refresh(); }, shell); return () => context.revert(); }, []); return <div ref={shell}><Navbar />{children}<Footer /></div> }